---
# tasks file for zabbix-agent
- name: Install the Zabbix repo.
  yum:
   name: https://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
   state: present
  register: zb_repo

- name: Install Zabbix Agent
  yum: name={{ zabbix_agent }} state=present
  notify: start zabbix-agent

- name: Ensure zabbix-agent is started and enabled to start at boot.
  service: name=zabbix-agent state=started enabled=yes
